functions/accounts.js, functions/resolvers/userResolvers.js, functions/typeDefs/mutation.js, functions/typeDefs/query.js
- Add `usersCount` query
- Add `UsersFilter` for `users` query
- Remove `password` input for `createAdmin` and `adminCreateUser` mutations
```gql
query users($filter: UsersFilter) {
users(filter: $filter) {
data {
id
firstName
middleName
lastName
isAdmin
schoolIdNumber
student {
id
}
teacher {
id
}
emails {
address
}
}
}
}
```
```gql
query {
usersCount {
usersCount
teachersCount
studentsCount
}
}
```
=> changes for admin

functions/resolvers/courseResolvers.js, functions/resolvers/postResolvers.js, functions/typeDefs/query.js, functions/typeDefs/types.js
query{
coursePosts(courseId: "ID"){
data{
content
tags
}
}
}
=> AddCoursePosts

functions/models/activity.js, functions/models/groupActivity.js, functions/models/groupSubmission.js, functions/models/post.js, functions/models/submission.js, functions/models/task.js, functions/resolvers/activityResolvers.js, functions/resolvers/postResolvers.js, functions/typeDefs/types.js
=> Posts changes

functions/resolvers/postResolvers.js, functions/typeDefs/query.js
=> AddGroupPosts (#39)

functions/models/comment.js, functions/resolvers/commentResolvers.js, functions/resolvers/index.js, functions/resolvers/postResolvers.js, functions/typeDefs/mutation.js, functions/typeDefs/query.js, functions/typeDefs/types.js
- add `createPostComment` mutation
- add `postComments` query
- add `comments` field under `Post`
```gql
mutation {
createPostComment(
postId: "61520f60ddd9c57284882108"
content: "adascsacsasadas"
) {
id
post {
id
content
comments {
data {
id
content
}
}
}
}
}
}
```
```gql
query {
postComments(postId: "61520f60ddd9c57284882108") {
data {
id
content
}
}
```
=> add comments stuff for posts

functions/resolvers/commentResolvers.js, functions/typeDefs/mutation.js, functions/typeDefs/types.js
- add `voteComment` mutation
- add `vote` field to `Comment`
```gql
mutation {
voteComment(
commentId: "6153485e839b10674c34d6af"
vote: 0
) {
id
content
vote
score
}
}
```
=> add voteComment mutation. add vote field to comment

functions/resolvers/feedResolvers.js, functions/typeDefs/query.js
Displays the logged-in teacher's course Posts
{
teacherHomeFeed{
data{
content
user{
firstName
lastName
}
course{
courseCode
name
}
group{
name
}
}
}
}
=> Add-teacherHomeFeed

functions/resolvers/fileResolvers.js, functions/typeDefs/query.js
- add `classGroupFiles` query
```gql
query {
classGroupFiles(groupId: "61449acc8c656b428b9b2930") {
postFiles {
user {
id
firstName
}
attachment
}
groupActivityFiles {
attachment
}
}
}
```
=> add classGroupFiles query

functions/models/task.js, functions/resolvers/groupSubmissionResolvers.js, functions/resolvers/index.js, functions/resolvers/taskResolvers.js, functions/typeDefs/mutation.js, functions/typeDefs/types.js
- New mutations
- `createTask`
- `changeTaskStatus`
- `submitTask`
- Add `tasks` and `myTask` under `GroupSubmission`
```gql
mutation {
createTask(
groupSubmissionId: "617ed6617b4832767e5fffc9"
studentId: "613e14d7792b190be6b49f4f"
description: "test",
dueAt: "2022-12-12"
) {
id
dueAt
}
}
```
```gql
mutation {
changeTaskStatus(taskId: "617fe165bb79b9451805d57c", status: IN_PROGRESS) {
id
status
}
}
```
```gql
mutation {
submitTask(taskId: "617fe165bb79b9451805d57c", attachment: "{}") {
id
attachment
}
}
```
```gql
query {
groupSubmission(groupSubmissionId: "617ed6617b4832767e5fffc9") {
id
tasks {
data {
id
}
}
myTask {
id
status
}
}
}
```
=> Task stuff

functions/resolvers/activityResolvers.js, functions/resolvers/postResolvers.js, functions/resolvers/submissionResolvers.js, functions/resolvers/taskResolvers.js, functions/resolvers/userResolvers.js, functions/typeDefs/mutation.js, functions/utils/cloudinary.js
- create `changeProfilePicture` mutation
```gql
mutation {
changeProfilePicture(profilePicture: "{\"public_id\":\"adasas\"}") {
id
profilePicture
}
}
```
=> changeProfilePicture mutation

functions/resolvers/userResolvers.js, functions/typeDefs/mutation.js
```
mutation{
editUserInfo(firstName: "", middleName: "", lastName: ""){
id
firstName
middleName
lastName
}
}
```
=> add edit user info mutation

functions/resolvers/activityResolvers.js
- automatically create `GroupSubmission` when calling `createGroupActivity`
=> create group submissions after group activity

functions/resolvers/taskResolvers.js, functions/typeDefs/query.js
- add `task` query
```gql
query {
task(taskId: "617fe165bb79b9451805d57c") {
id
student {
user {
id
firstName
}
}
}
}
```
=> add task query

functions/resolvers/courseResolvers.js, functions/typeDefs/mutation.js
```
mutation {
editCourseInfo(
courseId: ""
name: ""
subjCode: ""
yearAndSection: ""
startsAt: ""
endsAt: ""
isActive: true
) {
name
subjCode
yearAndSection
courseCode
startsAt
endsAt
isActive
}
}
```
=> added editcourseinfo mutation

functions/resolvers/userResolvers.js, functions/typeDefs/mutation.js
```
mutation {
editUserInfo(
firstName: ""
middleName: ""
lastName: ""
email: ""
){
firstName
middleName
lastName
emails{
address
}
}
}
```
=> Editemailinfo

functions/resolvers/courseResolvers.js, functions/typeDefs/query.js
- add `courseActivitiesAndSubmissions` query
```gql
query {
courseActivitiesAndSubmissions(
courseId: "613baeecf7d3510f2f1b0682"
studentId: "613a16292f1da209e4520635"
) {
data {
activity {
id
title
}
submission {
id
description
}
}
}
}
```
=> add new courseActivitiesAndSubmissions query

functions/typeDefs/mutation.js, functions/typeDefs/types.js
=> add year level

functions/resolvers/userResolvers.js, functions/typeDefs/mutation.js
```
mutation{
adminEditUserInfo(id: "", firstName: "", middleName:"", lastName:"", email:""){
firstName
middleName
lastName
emails{
address
}
}
}
```
=> add adminEditUserInfo

functions/resolvers/feedResolvers.js, functions/resolvers/userResolvers.js, functions/typeDefs/mutation.js, functions/typeDefs/query.js
```gql
query {
agendaRightSidePanel {
tasks {
id
description
dueAt
submittedAt
}
activities {
id
description
dueAt
mySubmission {
id
}
} 
groupActivities {
id
description
dueAt
}
}
}
```
=> Add agenda query and add year level (adminEditUserInfo)

functions/models/user.js, functions/typeDefs/mutation.js, functions/typeDefs/types.js
=> change section (int to string)
